version: '3.8'

services:
  angular-app:
    build: ./angular-docker/angular-docker-demo
    ports:
      - "4200:80"
    depends_on:
      - dotnet-app

  dotnet-app:
    build: ./dotnet-docker
    ports:
      - "5000:80"

